language: go
go:
- 1.11.x
sudo: required
services:
- docker
script:
- export GO111MODULE=on
- make setup linter-install
- make ci
- make
after_success:
- export REPO=navitia/sytralrt
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- make docker
- docker tag $REPO:$(make version) $REPO:$TAG
- docker tag $REPO:$(make version) $REPO:travis-$TRAVIS_BUILD_NUMBER
- if [ -n "$DOCKER_USER" ] && [ -n "$DOCKER_PASS" ]; then docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push $REPO; fi
env:
  global:
    - secure: "F9Op5gs+zUnVMeua4ngzf5m1lJq9RATbRyyUgZunzPBANdGJRc1VXJgNb9zSVEwqF1abbFgdQ9O6N9+p2Q5P+HT89NGGCrLf6jTpSiNLVEzOu97P4Ffra01GqVEzuzuQlZ6tFypo3IgNYjPXUvkiB8fxtklRTAHE5xX3mgi8k65LdsX2E3RKs0kBhnCE3NDm79pY+XVZnxzFLTjDXQeyXqS5CzZklavAOIW/aTNnQztHBeYKc/ROLq+jm48kWn7IUsmM7YJ1m4Sof6L/O9YsmE1dsc4FBe7+Z40+3qpYtJFS/BFBs2fo3Y3BOi3ryNVMxHIVVaZ4p2CP3TpMoEB8YE6RZUDEga6ExTC330Ql1F5qDRMYiA1wA6OM57eE6bqLujsKiVWOKeognEXKxW31Tu6JzftkPfbLg7l9wQ2eP1Tb6X7TidQbgbrRJf5BwtLoFEuYSk5Gpta7ShE2JAAOM/3qPYtEpsZMrHBdxVIVW77Y+36BiVtoPIVqXz7nR//aJWh9V/vvq91CikAu2VZ+T004U0KKED7WpzyfwphJkLMDNqJ8RHpGKCr3/wYbeudtDibpdCe66XLljlteOFeJkUGd+h5FZjOKLCb8ge4oPG9ETA5aLodmS8Zf7T4Xvea550DEfgt8EuB22DJyn8QajlaZjbUUWtrT4hKnvch+K+k="
    - secure: "u7AVxnKY2hTJXY/R1SVdstA+26ZytcWh2I8H0JWsbDkYEnWHHA3YurkDVtTVJg1/lMQBMHFHbzO8WEXNp2jS6aBCts2DtwG8nY/JzaClwRRefueXm4Ss5CxdZPnB72qRuSgYvJmf4zYTiiUyrTPCm3yO72wSHgUs65+xe/9Iqu9CokJQgXyPZNk3c9IJaqdm1QR2hbLGkGE4WR8JePWZigGIq8RH89nZJ8Qf8nDgdUtlrZHN3/AjkfnKhcANxgidjdyLhGLc5AII6STDnoyK2KRe41Wbth0rg14ZiHPmKJzPclhGclc3fL3im6RXAQRqazhLMuXf/w1P0j1O1QOM2NZ8ASZ2PNP4M4tfmR4mKhjFaaxa6IFpiDvaeW+LPgrHC+XUKfIIcYhKUIJgeEVdkltpI0OGXfr8y3sx6IGx6T5QwsWFq8xIsbR13KAeyknHTrkmvHIBHFtxlsDBkZWX7OTkQRH1eZga/wvuRtb0G+A2zU6eLJnZ8FEdTzBOa81SdY6SXPmXC8j+wRkCqDwBqGpUBPP7JVDCfOcPuxOb4CoN3Vmxv0EjlvKo4updOXsgv88hOHeWwKXNWlpdsNEmdTBfoHkk5uFXm+OYKb9LcVCg8Mr4uHShFgOzPdbAfPnO8m/JUmy9T6wl9jsfn3unB0Wo7BP5c8J0KjGKRr7lK+Y=" #DOCKER_USER
